{{- if and (and (.Values.portal.enabled) (not .Values.apim.dbLess)) (not (include "portal.externalConfig" .)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gravitee.portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.portal.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.portal.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if and .Values.common .Values.common.labels }}
    {{- range $key, $value := .Values.common.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  annotations:
    {{- if and .Values.common .Values.common.annotations }}
    {{- range $key, $value := .Values.common.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
data:
  use-gzip: "true"
  gzip-level: "5"
  gzip-types: "*"
  {{- if .Values.portal.configuration.files.config_json }}
  config.json: |-
    {{- .Values.portal.configuration.files.config_json | nindent 4 }}
  {{- else }}
  config.json: |
    {
      {{- if .Values.portal.baseURL }}
      "baseURL": "{{ .Values.portal.baseURL }}",
      {{- else }}
      "baseURL": "{{ .Values.api.ingress.portal.scheme }}://{{ index .Values.api.ingress.portal.hosts 0 }}{{ .Values.api.ingress.portal.path }}",
      {{- end }}
      {{- if .Values.portal.enforceEnvironmentId }}
      "environmentId": "{{ .Values.portal.enforceEnvironmentId }}",
      {{- end }}
      "loaderURL": "assets/images/gravitee-loader.gif",
      "pagination": {
        "size": {
          "default": 10,
          "values": [5, 10, 25, 50, 100]
        }
      }
    }
  {{- end }}
  {{- if .Values.portal.configuration.files.config_next_json }}
  config-next.json: |-
    {{- .Values.portal.configuration.files.config_next_json | nindent 4 }}
  {{- else }}
  config-next.json: |
    {
      {{- if .Values.portal.enforceEnvironmentId }}
      "environmentId": "{{ .Values.portal.enforceEnvironmentId }}",
      {{- end }}
      {{- if .Values.portal.baseURL }}
      "baseURL": "{{ .Values.portal.baseURL }}"
      {{- else }}
      "baseURL": "{{ .Values.api.ingress.portal.scheme }}://{{ index .Values.api.ingress.portal.hosts 0 }}{{ .Values.api.ingress.portal.path }}"
      {{- end }}
    }
  {{- end -}}
{{- end -}}
