#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
version: '3.5'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.0.1
    hostname: zookeeper-1
    container_name: zookeeper-1
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    networks:
      - kafka-cluster-network

  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.0.1
    hostname: zookeeper-2
    container_name: zookeeper-2
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    networks:
      - kafka-cluster-network


  zookeeper-3:
    image: confluentinc/cp-zookeeper:5.0.1
    hostname: zookeeper-3
    container_name: zookeeper-3
    ports:
      - "42181:42181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    networks:
      - kafka-cluster-network


  kafka-broker-1:
    image: confluentinc/cp-kafka:5.0.1
    hostname: kafka-broker-1
    container_name: kafka-broker-1
    ports:
      - "19093:19093"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-1:32181,zookeeper-1:42181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-broker-1:19093
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker-1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker-1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker-1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker-1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker-1_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}/broker-1:/etc/kafka/secrets
    networks:
      - kafka-cluster-network


  kafka-broker-2:
    image: confluentinc/cp-kafka:5.0.1
    hostname: kafka-broker-2
    container_name: kafka-broker-2
    ports:
      - "29093:29093"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-1:32181,zookeeper-1:42181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-broker-2:29093
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker-2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker-2_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker-2_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker-2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker-2_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}/broker-2:/etc/kafka/secrets
    networks:
      - kafka-cluster-network


  kafka-broker-3:
    image: confluentinc/cp-kafka:5.0.1
    hostname: kafka-broker-3
    container_name: kafka-broker-3
    ports:
      - "39093:39093"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-1:32181,zookeeper-1:42181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-broker-3:39093
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker-3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker-3_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker-3_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker-3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker-3_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ${KAFKA_SSL_SECRETS_DIR}/broker-3:/etc/kafka/secrets
    networks:
      - kafka-cluster-network

networks:
  kafka-cluster-network:
    driver: bridge
    name: kafka-cluster-network
