#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.8'

services:
  jest-e2e:
    image: cimg/node:16.10
    working_dir: /test
    volumes:
      - ./:/test
    command: npm run test:ci
    environment:
      - MANAGEMENT_BASE_PATH=http://management_api:8083/management
      - PORTAL_BASE_PATH=http://management_api:8083/portal/environments
      - GATEWAY_BASE_PATH=http://gateway:8082
      - WIREMOCK_BASE_PATH=http://wiremock:8080
    depends_on:
      management_api:
        condition: service_healthy
      gateway:
        condition: service_healthy
      wiremock:
        condition: service_started
    networks:
      - apim

  wiremock:
    image: wiremock/wiremock:2.33.2
    volumes:
      - ./api-test/resources/wiremock:/home/wiremock
    ports:
      - "8080:8080"
    networks:
      - apim
