resourcePackages:
  - io.gravitee.rest.api.management.rest.resource
cacheTTL: 0
openAPI:
  servers:
    - url: http://localhost:8083/management
  info:
    version: '${project.version}'
    title: Gravitee.io - Management API
    description: 'Some news resources are in alpha version. This implies that they are likely to be modified or even removed in future versions. They are marked with the ðŸ§ª symbol'
