dependencies:
  - name: elasticsearch
    version: 19.10.6
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: mongodb
    version: 13.16.2
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
